export const themeBg = '#fff'
export const themeText = '#000'
export const primaryBg = '#034748'
export const primaryText = '#fff'
export const secondaryBg = '#005E7C'
export const secondaryText = '#fff'